// Code generated by MockGen. DO NOT EDIT.
// Source: foods/food.go

// Package mock_foods is a generated GoMock package.
package mock_foods

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockFood is a mock of Food interface
type MockFood struct {
	ctrl     *gomock.Controller
	recorder *MockFoodMockRecorder
}

// MockFoodMockRecorder is the mock recorder for MockFood
type MockFoodMockRecorder struct {
	mock *MockFood
}

// NewMockFood creates a new mock instance
func NewMockFood(ctrl *gomock.Controller) *MockFood {
	mock := &MockFood{ctrl: ctrl}
	mock.recorder = &MockFoodMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFood) EXPECT() *MockFoodMockRecorder {
	return m.recorder
}

// Name mocks base method
func (m *MockFood) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name
func (mr *MockFoodMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockFood)(nil).Name))
}

// MockHoge is a mock of Hoge interface
type MockHoge struct {
	ctrl     *gomock.Controller
	recorder *MockHogeMockRecorder
}

// MockHogeMockRecorder is the mock recorder for MockHoge
type MockHogeMockRecorder struct {
	mock *MockHoge
}

// NewMockHoge creates a new mock instance
func NewMockHoge(ctrl *gomock.Controller) *MockHoge {
	mock := &MockHoge{ctrl: ctrl}
	mock.recorder = &MockHogeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockHoge) EXPECT() *MockHogeMockRecorder {
	return m.recorder
}

// Foo mocks base method
func (m *MockHoge) Foo(foo string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Foo", foo)
	ret0, _ := ret[0].(string)
	return ret0
}

// Foo indicates an expected call of Foo
func (mr *MockHogeMockRecorder) Foo(foo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Foo", reflect.TypeOf((*MockHoge)(nil).Foo), foo)
}
